### ISSUE TITLE
[core] Authentication improvements

### ISSUE THREAD

**Issue by bharatkashyap** [mui/toolpad#3877]
### To Do

- [x] #3930
- [x] #3931
- [ ]  RegisterPage component
- [ ]  ChangePasswordPage component
- [ ]  Allow customisation through a slots API
- [ ] Support multiple layout versions of the SignInPage
- [x]  Add email/magic links provider and build an example: https://next-auth.js.org/providers/email
- [ ] Add a Supabase auth example

**Search keywords**:
