### ISSUE TITLE
Add a template in material UI templates

### ISSUE THREAD

**Issue by bharatkashyap** [mui/toolpad#4153]
- Use the theme from https://github.com/zanivan/toolpad-core-theme
- (Optional) Host the example on the Toolpad docs under https://mui.com/toolpad/core/introduction/examples/

### Navigation Structure

```
{
  segment: "dashboard",
  title: "Dashboard",
 },
 {
   segment: "orders",
   title: "Orders", 
  },
  {
	 segment: "Support",
	 title: "Support",
	 children:  
	 [
	 {			
		 segment: "Tickets",
		 title: "tickets",
		 action: "<Chip label={12} color="success" size="small" />,"
	},
	{
	          segment: "Team",
                  title: "Team",
	}
        ]
}
```	 

### Flow

- `/dashboard` opens first, public page
- `/orders` is also public
- `/orders/team` requires signing in

### Page Content

Dashboard

- Use the charts/cards from the top half of https://mui.com/material-ui/getting-started/templates/dashboard/
<img src="https://github.com/user-attachments/assets/37028266-9465-40b6-bf48-05b269eca023" width=500 />

Orders, Users

- Use the grid and charts from the bottom half of https://mui.com/material-ui/getting-started/templates/dashboard/
<img src="https://github.com/user-attachments/assets/7f205b4f-a4c2-44fe-858c-3208f285828c" width=500 />

Sign In 

- Add `credentials` (along with OAuth and any others) so that someone can try it out instantly, add a callout with the demo credentials

<img src="https://github.com/user-attachments/assets/65d10a84-f4f0-4e06-96aa-d361f9012841" width=300 />

### Milestones

v0: Place it in https://mui.com/toolpad/core/introduction/examples/
- [x] https://github.com/mui/toolpad/issues/4065
- [x] https://github.com/mui/toolpad/issues/4066
- [x] https://github.com/mui/toolpad/issues/4067

v1: Place it in https://mui.com/material-ui/getting-started/templates/
- [x] https://github.com/mui/toolpad/issues/4147
- [x] https://github.com/mui/toolpad/issues/4102
- [x] https://github.com/mui/toolpad/issues/4101
